---
- name: Deploy Node.js Application on AWS EC2 (Ubuntu)
  hosts: ec2_server
  become: yes
  vars:
    app_repo: "https://github.com/priyabuss2004/node-app.git"
    app_dir: "/home/ubuntu/node-app"

  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - git
          - curl
        state: present

    - name: Add NodeSource APT repository
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
      args:
        executable: /bin/bash

    - name: Install Node.js (includes npm)
      ansible.builtin.apt:
        name:
          - nodejs
        state: present
        update_cache: yes

    - name: Clone the application repository
      ansible.builtin.git:
        repo: "{{ app_repo }}"
        dest: "{{ app_dir }}"
        version: main
        force: yes

    - name: Install npm dependencies
      ansible.builtin.shell: |
        npm install
      args:
        chdir: "{{ app_dir }}"

    - name: Start the Node.js application
      ansible.builtin.shell: |
        nohup npm start > app.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
      async: 30
      poll: 0

    - name: Confirm application started
      ansible.builtin.debug:
        msg: "✅ Node.js application deployed and started successfully on EC2 Ubuntu!"
